In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv("ecommerce_customer_data_large.csv")
df2 = pd.read_csv("ecommerce_customer_data_custom_ratios.csv")

df = pd.concat([df1, df2], ignore_index=True)

df.to_csv("df.csv", index=False)

In [3]:
df.head

<bound method NDFrame.head of         Customer ID        Purchase Date Product Category  Product Price  \
0             44605  2023-05-03 21:30:02             Home            177
1             44605  2021-05-16 13:57:44      Electronics            174
2             44605  2020-07-13 06:16:57            Books            413
3             44605  2023-01-17 13:14:36      Electronics            396
4             44605  2021-05-01 11:29:27            Books            259
...             ...                  ...              ...            ...
499995        33308  2023-08-10 13:39:06         Clothing            279
499996        48835  2021-11-23 01:30:42             Home             27
499997        21019  2020-07-02 14:04:48             Home             17
499998        49234  2020-12-30 02:02:40            Books            398
499999        16971  2021-03-13 16:28:35      Electronics            425

        Quantity  Total Purchase Amount Payment Method  Customer Age  Returns  \
0              1                   2427         PayPal            31      1.0
1              3                   2448         PayPal            31      1.0
2              1                   2345    Credit Card            31      1.0
3              3                    937           Cash            31      0.0
4              4                   2598         PayPal            31      1.0
...          ...                    ...            ...           ...      ...
499995         2                   2187         PayPal            55      1.0
499996         1                   3615    Credit Card            42      1.0
499997         5                   2466           Cash            41      0.0
499998         2                   3668         Crypto            34      0.0
499999         4                   2370           Cash            36      1.0

          Customer Name  Age  Gender  Churn
0           John Rivera   31  Female      0
1           John Rivera   31  Female      0
2           John Rivera   31  Female      0
3           John Rivera   31  Female      0
4           John Rivera   31  Female      0
...                 ...  ...     ...    ...
499995  Michelle Flores   55    Male      1
499996      Jeremy Rush   42  Female      1
499997       Tina Craig   41    Male      0
499998  Jennifer Cooper   34  Female      1
499999    Justin Lawson   36  Female      1

[500000 rows x 13 columns]>

In [4]:
df.info

<bound method DataFrame.info of         Customer ID        Purchase Date Product Category  Product Price  \
0             44605  2023-05-03 21:30:02             Home            177
1             44605  2021-05-16 13:57:44      Electronics            174
2             44605  2020-07-13 06:16:57            Books            413
3             44605  2023-01-17 13:14:36      Electronics            396
4             44605  2021-05-01 11:29:27            Books            259
...             ...                  ...              ...            ...
499995        33308  2023-08-10 13:39:06         Clothing            279
499996        48835  2021-11-23 01:30:42             Home             27
499997        21019  2020-07-02 14:04:48             Home             17
499998        49234  2020-12-30 02:02:40            Books            398
499999        16971  2021-03-13 16:28:35      Electronics            425

        Quantity  Total Purchase Amount Payment Method  Customer Age  Returns  \
0              1                   2427         PayPal            31      1.0
1              3                   2448         PayPal            31      1.0
2              1                   2345    Credit Card            31      1.0
3              3                    937           Cash            31      0.0
4              4                   2598         PayPal            31      1.0
...          ...                    ...            ...           ...      ...
499995         2                   2187         PayPal            55      1.0
499996         1                   3615    Credit Card            42      1.0
499997         5                   2466           Cash            41      0.0
499998         2                   3668         Crypto            34      0.0
499999         4                   2370           Cash            36      1.0

          Customer Name  Age  Gender  Churn
0           John Rivera   31  Female      0
1           John Rivera   31  Female      0
2           John Rivera   31  Female      0
3           John Rivera   31  Female      0
4           John Rivera   31  Female      0
...                 ...  ...     ...    ...
499995  Michelle Flores   55    Male      1
499996      Jeremy Rush   42  Female      1
499997       Tina Craig   41    Male      0
499998  Jennifer Cooper   34  Female      1
499999    Justin Lawson   36  Female      1

[500000 rows x 13 columns]>

In [5]:
df.isnull().sum()

Customer ID                  0
Purchase Date                0
Product Category             0
Product Price                0
Quantity                     0
Total Purchase Amount        0
Payment Method               0
Customer Age                 0
Returns                  94978
Customer Name                0
Age                          0
Gender                       0
Churn                        0
dtype: int64

In [6]:
df['Returns'].dtype

dtype('float64')

In [7]:
df[['Customer ID', 'Returns']].head()

   Customer ID  Returns
0        44605      1.0
1        44605      1.0
2        44605      1.0
3        44605      0.0
4        44605      1.0

In [8]:
df['Returns'] = df['Returns'].fillna(0)

In [9]:
df.isnull().sum()

Customer ID              0
Purchase Date            0
Product Category         0
Product Price            0
Quantity                 0
Total Purchase Amount    0
Payment Method           0
Customer Age             0
Returns                  0
Customer Name            0
Age                      0
Gender                   0
Churn                    0
dtype: int64

In [10]:
df.columns = df.columns.str.lower()

In [11]:
df.columns

Index(['customer id', 'purchase date', 'product category', 'product price',
       'quantity', 'total purchase amount', 'payment method', 'customer age',
       'returns', 'customer name', 'age', 'gender', 'churn'],
      dtype='object')

In [12]:
df = df.drop("customer age", axis=1)

In [13]:
df.columns

Index(['customer id', 'purchase date', 'product category', 'product price',
       'quantity', 'total purchase amount', 'payment method', 'returns',
       'customer name', 'age', 'gender', 'churn'],
      dtype='object')

In [14]:
labels = ['teenage','young','middle_age','old']
df['age_group']=pd.qcut(df['age'],q=4, labels =labels)

In [15]:
df[['age','age_group']].head(10)

   age age_group
0   31     young
1   31     young
2   31     young
3   31     young
4   31     young
5   27   teenage
6   27   teenage
7   27   teenage
8   27   teenage
9   27   teenage

In [16]:
#connect to the server MySQL
!pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\users\aqsa-amir\anaconda3\lib\site-packages (2.9.13)
Requirement already satisfied: sqlalchemy in c:\users\aqsa-amir\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\aqsa-amir\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\aqsa-amir\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)

In [17]:
pip install sqlalchemy pymysql pandas

Requirement already satisfied: sqlalchemy in c:\users\aqsa-amir\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: pymysql in c:\users\aqsa-amir\anaconda3\lib\site-packages (1.2.3)
Requirement already satisfied: pandas in c:\users\aqsa-amir\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: greenlet>=1 in c:\users\aqsa-amir\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\aqsa-amir\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\aqsa-amir\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\aqsa-amir\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\aqsa-amir\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\aqsa-amir\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\aqsa-amir\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [18]:
!pip install pymysql sqlalchemy

Requirement already satisfied: pymysql in c:\users\aqsa-amir\anaconda3\lib\site-packages (1.2.3)
Requirement already satisfied: sqlalchemy in c:\users\aqsa-amir\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\aqsa-amir\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\aqsa-amir\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)

In [19]:
from urllib.parse import quote_plus
from sqlalchemy import create_engine

username = "root"
password = quote_plus("@mysqlpassword3")
host = "127.0.0.1"
port = 3306
database = "e_commerece"

engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
)

In [20]:
table_name = "df"   # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'df' in database 'e_commerece'.